server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    testWhileIdle: true
    validateQuery: SELECT 1
  jpa:
    default_schema: test
    hibernate.ddl-auto: validate
    hibernate.show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect