server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-demo-jpa-liqibase
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: validate
    properties:
      default_schema: spring-boot-demo-jpa-liqibase
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  liquibase:
    default-schema: spring-boot-demo-jpa-liqibase