server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: validate
    properties:
      default_schema: demo
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  liquibase:
    #enabled: false
    default-schema: demo